"""SQLite access helpers.

Analytics and the AI assistant read through a **read-only** connection so
that no query — including any SQL generated by the LLM — can ever modify
the database. This is the primary safety guarantee behind the agent's SQL
tool (see CLAUDE.md sec. 25, "Agent Safety").
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

import pandas as pd

from . import config


def _require_db() -> Path:
    db_path = Path(config.DB_PATH).resolve()  # Resolve to absolute path
    if not db_path.exists():
        raise FileNotFoundError(
            f"Database not found at {db_path}.\n"
            "Build it first with:  python scripts/load_data.py"
        )
    return db_path


def get_connection(readonly: bool = True) -> sqlite3.Connection:
    """Open a connection to the SQLite database.

    ``readonly=True`` (the default) opens the file with SQLite's ``mode=ro``
    URI so writes are rejected at the driver level.
    """
    db_path = _require_db()
    if readonly:
        # as_uri() yields an absolute file:// URI with proper percent-encoding
        # (the project path contains spaces), which SQLite decodes correctly.
        conn = sqlite3.connect(f"{db_path.as_uri()}?mode=ro", uri=True)
    else:
        conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn


def query_df(sql: str, params: tuple | dict | None = None) -> pd.DataFrame:
    """Run a read-only query and return the result as a DataFrame."""
    with get_connection(readonly=True) as conn:
        return pd.read_sql_query(sql, conn, params=params)


def query_rows(sql: str, params: tuple | dict | None = None) -> list[dict]:
    """Run a read-only query and return a list of plain dict rows."""
    with get_connection(readonly=True) as conn:
        cur = conn.execute(sql, params or ())
        return [dict(r) for r in cur.fetchall()]
